# Generated by Django 3.2.9 on 2021-11-13 00:25

from django.db import migrations, models
import msgserver.models


class Migration(migrations.Migration):

    dependencies = [
        ('msgserver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.AlterField(
            model_name='message',
            name='key',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, validators=[msgserver.models.validate_key]),
        ),
        migrations.AlterField(
            model_name='message',
            name='msg',
            field=models.CharField(max_length=160),
        ),
    ]
